services:
  - type: web
    name: atividade-crud-api
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/saude
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: CORS_ORIGIN
        value: "*"
